<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MyTurnMod.Core</AssemblyName>
    <RootNamespace>MyTurnMod.Core</RootNamespace>
  </PropertyGroup>

</Project>
